package com.example.attend.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

@Entity
@Getter
@Setter   // ✅ ensures all setters including setSession() are generated
@NoArgsConstructor
@Table(
    indexes = {
        @Index(columnList = "session_id"),
        @Index(columnList = "studentUsername")
    }
)
public class Attendance {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Relation to session
    @ManyToOne(optional = false)
    @JoinColumn(name = "session_id")   // ensures proper FK column
    private Session session;           // ✅ setter/getter generated by Lombok

    // Student info (redundant for reporting speed)
    private String studentUsername;
    private String studentId;
    private String studentName;

    // Metadata about the check-in
    private Instant submittedAt;

    private Double lat;
    private Double lng;
    private Double accuracyMeters;

    private String ipTruncated;   // anonymized IP (/24 or /64)
    private String deviceHash;    // fingerprint hash

    // Flags for validation
    private boolean flagLate;
    private boolean flagGeofence;
    private boolean flagLowAccuracy;

    private String flagNote;      // explanation message
}
